export const SIGN_IN_URL =
  "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyAPbpI-9_gUryz9fYusEFdRdIaAkQ9f5H0";
export const SIGN_UP_URL =
  "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=AIzaSyAPbpI-9_gUryz9fYusEFdRdIaAkQ9f5H0";
export const DATABASE_URL = "https://health-record-37274.firebaseio.com/";
export const GET_USER_INFO =
  "https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=AIzaSyAPbpI-9_gUryz9fYusEFdRdIaAkQ9f5H0";
export const UPDATE_USER_INFO =
  "https://identitytoolkit.googleapis.com/v1/accounts:update?key=AIzaSyAPbpI-9_gUryz9fYusEFdRdIaAkQ9f5H0";
export const SERVER_URL = "http://34.68.68.81:3001";
export const REGISTER_CLIENT_URL = `${SERVER_URL}/users/registerClient`;
export const REGISTER_DOCTOR_URL = `${SERVER_URL}/users/registerDoctor`;
export const GET_ACCESS_LIST_URL = `${SERVER_URL}/users/getAccessList`;
export const GET_ALLOWED_LIST_URL = `${SERVER_URL}/users/getAllowedList`;
export const CHECK_PERMISSION_URL = `${SERVER_URL}/users/checkPermissionStatus`;
export const GET_DOCTOR_LIST_URL = `${SERVER_URL}/users/getDoctorList`;
export const ADD_PERMISSION_URL = `${SERVER_URL}/users/addPermission`;
export const DELETE_PERMISSION_URL = `${SERVER_URL}/users/deletePermission`;
export const CREATE_DOCTOR_RECORD_URL = `${SERVER_URL}/record/createdoctor`;
export const CREATE_PATIENT_RECORD_URL = `${SERVER_URL}/record/createpatient`;
export const ADD_MEDICAL_INFO_URL = `${SERVER_URL}/record/addmedicalinfo`;
export const GET_MEDICAL_INFO_URL = `${SERVER_URL}/record/getmedicalinfo`;
