export const SIGN_IN_URL =
  "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=AIzaSyAPbpI-9_gUryz9fYusEFdRdIaAkQ9f5H0";
export const SIGN_UP_URL =
  "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=AIzaSyAPbpI-9_gUryz9fYusEFdRdIaAkQ9f5H0";
export const DATABASE_URL = "https://health-record-37274.firebaseio.com/";
export const GET_USER_INFO =
  "https://identitytoolkit.googleapis.com/v1/accounts:lookup?key=AIzaSyAPbpI-9_gUryz9fYusEFdRdIaAkQ9f5H0";
export const UPDATE_USER_INFO =
  "https://identitytoolkit.googleapis.com/v1/accounts:update?key=AIzaSyAPbpI-9_gUryz9fYusEFdRdIaAkQ9f5H0";
export const SERVER_URL = "http://35.239.146.52:3001";
export const REGISTER_CLIENT_URL = `${SERVER_URL}/users/registerClient`;
export const REGISTER_DOCTOR_URL = `${SERVER_URL}/users/registerDoctor`;
